---
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafezinho-api
    ports:
      - 5027:5027
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="server=db;port=3306;database=cafezinho_letras_db;user=root;password=#2025cafezinho"
    networks:
      - cafezinho-network
  db:
    image: mysql:8.0
    container_name: cafezinho-letras-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "#2025cafezinho"
      MYSQL_DATABASE: cafezinho_letras_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cafezinho-network
networks:
  cafezinho-network:
    driver: bridge
volumes:
  db_data: null
