# docker-compose para rodar localmente/dev com hot-reload
---
services:
  api:
    #build:
      #context: .
      #dockerfile: Dockerfile
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: cafezinho-api
    working_dir: /app
    ports:
      - 5027:5027
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=cafezinho_letras_db;User=root;Password=_2025cafezinho
    networks:
      - cafezinho-network
    volumes:
      -  ./:/app
    command: dotnet watch run --urls=http://+:5027
  db:
    image: mysql:8.0
    container_name: cafezinho-letras-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: _2025cafezinho
      MYSQL_DATABASE: cafezinho_letras_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cafezinho-network
networks:
  cafezinho-network:
    driver: bridge
volumes:
  db_data: null
